// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Container: typeof import('./src/components/Container/Container.vue')['default'];
    ElCard: typeof import('element-plus/es')['ElCard'];
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader'];
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar'];
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default'];
    PokemonCard: typeof import('./src/components/PokemonCard/PokemonCard.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll'];
    vLoading: typeof import('element-plus/es')['ElLoadingDirective'];
  }
}
